# Generated by Django 5.2.4 on 2025-07-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentLoc', models.CharField(default='', max_length=1000)),
                ('destination', models.CharField(default='', max_length=1000)),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('travelTime', models.IntegerField(db_default=0, default=0)),
                ('travelMode', models.CharField(default='', max_length=10)),
                ('travelError', models.IntegerField(db_default=0, default=0)),
                ('tolCost', models.IntegerField(db_default=0, default=0)),
            ],
        ),
    ]
